module.exports = {
  FrozenRange: require('./FrozenRange.js'),
  Set: require('./Set.js'),
  SingletonSet: require('./SingletonSet.js'),
  classOf: require('./classOf.js'),
  enumeration: require('./enumeration.js'),
  findAllIndex: require('./findAllIndex.js'),
  foreach: require('./foreach.js'),
  freezeProps: require('./freezeProps.js'),
  hideProps: require('./hideProps.js'),
  inherit: require('./inherit.js'),
  isFalsy: require('./isFalsy.js'),
  isFunction: require('./isFunction.js'),
  isNaN: require('./isNaN.js'),
  quacks: require('./quacks.js'),
};
